### ISSUE TITLE
ComponentModeller does not seem to have consitent hash

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1262]
How can we make sure two Component Modellers have the same hash?

When running same Component Modeller twice im getting different hashes

i was trying to use the hash as the simulation id for a file cache

https://github.com/gdsfactory/gplugins/pull/239/commits/1e457721794946a9decf8bcdabf6ec401cb82096

@yaugenst

**Comment by yaugenst** [comment]
The hash of the `ComponentModeler` seems to be different across Python interpreter instances (which is default hashing behavior, there is a hash seed attached to each interpreter). I'm not sure if this is intended for the `ComponentModeler` class though.

You can fix it by hashing the modeler's JSON directly, e.g. like so:

```python
import hashlib
hashlib.md5(modeler.json().encode()).hexdigest()
```

**Comment by tylerflex** [comment]
I just fixed this in this PR. https://github.com/flexcompute/tidy3d/pull/1259. It should work for component modeler hashing general but worth a test.

**Comment by momchil-flex** [comment]
It seems like this does not fully fix Joaquin's issue? The `hash(modeler)` output would still be different?

**Comment by momchil-flex** [comment]
The reason we stopped using the json for the hash is because we exclude custom components that are defined as arrays from the json right?

And we did that to save on space e.g. when writing the json to hdft?

Maybe we can introduce an option to write the data, and use that "full json" for the hash. That would make it slower in some cases, but maybe the best option still? We should just make sure it doesn't slow anything important down.

**Comment by yaugenst** [comment]
If it helps, I do the following to hash simulations, and I guess the `ComponentModeler` could be handled in the same way:

```python
import io
import base64

bf = io.BytesIO()
simulation.to_hdf5(bf)
hashval = sha256(bf.getvalue()).hexdigest()
```

This avoid the disk I/O but might still be somewhat slow if there is a lot of data of course.

**Comment by joamatab** [comment]
that worked great, thank you Yannick!

**Comment by tylerflex** [comment]
I changed the PR to add @yaugenst 's hashing function as a Tidy3DBaseModel method `_hash_self()`, once that is released you can simply call that if you need a hashing function for tidy3d components that is the same every session.

**Comment by yaugenst** [comment]
Hi @tylerflex, glad to hear that this was useful! To add some context, we are doing it this way because this is the key that we use to cache simulations in our backend. The reason why we are not implementing `__hash__` is because Python hashes are 64 bit wide (no matter the underlying method used), and that has a 50% collision chance at ~5e9 hashes. In our case that would probably still be fine because we aren't running that many simulations, but in your case I imagine that would become a problem. So sha256 seems like a good choice, especially considering that git is moving towards that too.

One problem with hashing the full file is that we are probably hashing things that might safely be allowed to change, e.g. minor version numbers. A better approach would probably be excluding particular entries from the hash to maximize (valid) cache hits.

**Comment by momchil-flex** [comment]
> One problem with hashing the full file is that we are probably hashing things that might safely be allowed to change, e.g. minor version numbers. A better approach would probably be excluding particular entries from the hash to maximize (valid) cache hits.

For that specific example, you may or may not want to cache this... There could be some differences in the results across different minor versions, e.g. due to bugfixes. Also, while we ensure that a 2.y version can load data for a 2.x version, when y>x, the reverse is not true. So a 2.x version pulling a cached simulation data file that was run with 2.y will likely error when trying to load it.

**Comment by yaugenst** [comment]
Yeah for sure, my example was probably not great. You guys will know best whether or not there are keys that are allowed to change and yield valid identical results. Maybe there aren't any either. Just from a efficiency perspective it might be worth to consider though.

**Comment by momchil-flex** [comment]
Yeah, I actually can't come up with anything right now, apart from numerical precision potentially (e.g. for some reason something was read as a 1.00000000000002 instead of 0.99999999999998 :) ). In that sense an "almost_equal" check could be useful, but that seems complicated.
