### ISSUE TITLE
Fix mode solver divide by zero warning

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#711]

**Comment by momchil-flex** [comment]
What is this about?

**Comment by tylerflex** [comment]
see cell [7], this pops up a lot in our notebooks and in the tests.
https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/ModeSolver.html

**Comment by momchil-flex** [comment]
I just ran this notebook using 1.9.0rc2 and I do not get such a warning message. What's your numpy version?
![image](https://user-images.githubusercontent.com/92756559/220773717-85e3f9ef-aea6-4320-8227-c6c028a3ab43.png)

**Comment by tylerflex** [comment]
1.24.2

maybe it's fixed now? tom was seeing it too and I get it when I run tests.

**Comment by momchil-flex** [comment]
Weird. I tried with 1.24.2 and still not getting it. I had scipy 1.8.1, updated to 1.10.1, didn't get it on either. I also looked at the logs from the most recent github tests and it doesn't seem like the warning gets printed in their execution.

**Comment by momchil-flex** [comment]
I don't think it's fixed though, but I'm not sure what exactly in the system configuration causes it to happen...

**Comment by tylerflex** [comment]
I was able to reproduce this in my system as
```py
import numpy as np
arr = np.eye(3) + 0j
np.linalg.det(arr)
```
```
/Users/twhughes/.pyenv/versions/3.10.9/lib/python3.10/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: divide by zero encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/twhughes/.pyenv/versions/3.10.9/lib/python3.10/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: invalid value encountered in det
```
maybe it's a numpy bug? my guess is it's something to do with the fact that `arr` is complex with 0 imaginary component. Maybe the determinant algorithm is dividing by zero in some case. I don't get this error if `arr` is purely real.
